language: scala

scala:
  - 2.10.2

# only trigger builds on master
branches:
  only:
    - master
    - v1.0.x

script:
  - "sbt test blue-test/scenario:test"
  - "node_modules/karma/bin/karma start blue-web/src/main/resources/test/config/karma.conf.js --single-run --port 33333"

services:
    - couchdb

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq jsvc
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - sh -e /etc/init.d/xvfb start
  - npm install karma
  - npm install karma-jasmine karma-chrome-launcher --save-dev

before_script:
  - "echo \"couchdb := None\n\ncouchPort := 5984\n\" > build.sbt"

after_script:
  - "cat /tmp/bluelatex.err"
